version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --config _config.yml --watch --force_polling --verbose -l --unpublished
    ports:
        - 4000:4000
    volumes:
        - ".:/srv/jekyll"
